require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe HostsController do

  def mock_host(stubs={})
    @mock_host ||= mock_model(Host, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all hosts as @hosts" do
      Host.stub(:all) { [mock_host] }
      get :index
      assigns(:hosts).should eq([mock_host])
    end
  end

  describe "GET show" do
    it "assigns the requested host as @host" do
      Host.stub(:find).with("37") { mock_host }
      get :show, :id => "37"
      assigns(:host).should be(mock_host)
    end
  end

  describe "GET new" do
    it "assigns a new host as @host" do
      Host.stub(:new) { mock_host }
      get :new
      assigns(:host).should be(mock_host)
    end
  end

  describe "GET edit" do
    it "assigns the requested host as @host" do
      Host.stub(:find).with("37") { mock_host }
      get :edit, :id => "37"
      assigns(:host).should be(mock_host)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created host as @host" do
        Host.stub(:new).with({'these' => 'params'}) { mock_host(:save => true) }
        post :create, :host => {'these' => 'params'}
        assigns(:host).should be(mock_host)
      end

      it "redirects to the created host" do
        Host.stub(:new) { mock_host(:save => true) }
        post :create, :host => {}
        response.should redirect_to(host_url(mock_host))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved host as @host" do
        Host.stub(:new).with({'these' => 'params'}) { mock_host(:save => false) }
        post :create, :host => {'these' => 'params'}
        assigns(:host).should be(mock_host)
      end

      it "re-renders the 'new' template" do
        Host.stub(:new) { mock_host(:save => false) }
        post :create, :host => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested host" do
        Host.stub(:find).with("37") { mock_host }
        mock_host.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :host => {'these' => 'params'}
      end

      it "assigns the requested host as @host" do
        Host.stub(:find) { mock_host(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:host).should be(mock_host)
      end

      it "redirects to the host" do
        Host.stub(:find) { mock_host(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(host_url(mock_host))
      end
    end

    describe "with invalid params" do
      it "assigns the host as @host" do
        Host.stub(:find) { mock_host(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:host).should be(mock_host)
      end

      it "re-renders the 'edit' template" do
        Host.stub(:find) { mock_host(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested host" do
      Host.stub(:find).with("37") { mock_host }
      mock_host.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the hosts list" do
      Host.stub(:find) { mock_host }
      delete :destroy, :id => "1"
      response.should redirect_to(hosts_url)
    end
  end

end
